version: '2'
services:
  db:
    image: mongo
    command: "mongod"
  library:
    build:
      context: .
      dockerfile: Dockerfile
    command: node_modules/.bin/nodemon --exec npm start
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - .:/home/app/library
      - /home/app/library/node_modules
    links:
      - db
